
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 13 12:48:38 CEST 2024
//----------------------------------------------------

package ast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int CCIERRE = 21;
  public static final int PCIERRE = 19;
  public static final int LCIERRE = 23;
  public static final int LAP = 22;
  public static final int RESTA = 5;
  public static final int CAP = 20;
  public static final int PUNTOCOMA = 26;
  public static final int LISTX = 29;
  public static final int FOR = 39;
  public static final int WRITE = 42;
  public static final int NOT = 17;
  public static final int AND = 10;
  public static final int IGUAL = 24;
  public static final int VOIDX = 33;
  public static final int OR = 9;
  public static final int DIV = 7;
  public static final int SUMA = 4;
  public static final int MAIN = 40;
  public static final int IF = 36;
  public static final int AMPERSAND = 28;
  public static final int ID = 45;
  public static final int EOF = 0;
  public static final int BOOLX = 32;
  public static final int RETURN = 35;
  public static final int AST = 6;
  public static final int TRUE = 2;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int COMA = 25;
  public static final int MENOR = 14;
  public static final int MOD = 8;
  public static final int INTX = 31;
  public static final int EQ = 11;
  public static final int MAYOR = 13;
  public static final int ENT = 44;
  public static final int PAP = 18;
  public static final int FLECHA = 27;
  public static final int ELSE = 37;
  public static final int READ = 41;
  public static final int WHILE = 38;
  public static final int MENEQ = 16;
  public static final int ALIAS = 43;
  public static final int STRUCTX = 30;
  public static final int FALSE = 3;
  public static final int MAYEQ = 15;
  public static final int NOTEQ = 12;
}

